import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
// The Claude Agent SDK is ESM and calls createRequire(import.meta.url) at load.
// Bundled into this CJS file, import.meta.url would be undefined and throw, so we
// shim it to this file's URL (Obsidian loads plugins as CommonJS modules).
const import_meta_url = typeof __filename !== "undefined"
	? require("url").pathToFileURL(__filename).href
	: "file:///";
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: {
		"import.meta.url": "import_meta_url",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Node built-ins are provided by Obsidian's Electron runtime. The Agent
		// SDK imports them with the "node:" prefix, so externalize both forms.
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`)],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
